name: ci

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: razriar/repo:latest
      - name: Pull and deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: | 
            docker kill server &&
            docker rm server &&
            docker pull razriar/repo && 
            docker run -d --network=host --name server razriar/repo
          host: ${{ secrets.HOST }}
          username: root
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
      - name: Notify failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Repository: ${{ github.repository }}
            Deploy failure
      - name: Notify success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Repository: ${{ github.repository }}
            Deploy success
