name: Release
on:
  push:
    branches: [ main, alpha, beta ]
  pull_request:
    branches: [ main, alpha, beta ]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        branches: |    
          [
            'main',
            {
              name: 'beta', 
              prerelease: true
            }, 
            {
              name: 'alpha', 
              prerelease: true
            }
          ]
        extra_plugins: |
          @semantic-release/commit-analyzer
          @semantic-release/release-notes-generator
          @semantic-release/changelog
          @semantic-release/git
